version: '3.1'
services:
  # back:
  #   build: back
  #   ports:
  #     - '4201:4201'
  #   volumes:
  #     - './back/app/srcs:/app/srcs'
  #   depends_on:
  #     - mongo
  #   environment:
  #     - PORT=4201
  #     - 'DB_HOST=mongodb://mongo'
  #     - DB_PORT=27017
  #     - DB_NAME=test
  #     - DB_USER=root
  #     - DB_PASSWORD=example
  #   networks:
  #     - default

  front:
    build: front
    ports:
      - '3001:3001'
    # volumes:
    #   - './front/src'

    # depends_on:
    #   - back
    networks:
      - default
    environment:
      - CHOKIDAR_USEPOLLING=true
      # - "BACK_HOST=back:3001"
      - DOCKER_HOST=${DOCKER_HOST}
  #   tty: true
#    logging:
#      driver: none

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - default
    logging:
      driver: none
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '18081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - default
    logging:
      driver: none

networks:
  default:
    driver: "bridge"
